Repository astrochun/Metallicity_Stack_Commons, pull requests merged in 2020-06, with the labels that each got.

#53 release/1.1.0
  Metallicity_Stack_Commons/__init__.py
  Metallicity_Stack_Commons/analysis/attenuation.py
  Metallicity_Stack_Commons/analysis/error_prop.py
  Metallicity_Stack_Commons/analysis/ratios.py
  Metallicity_Stack_Commons/column_names.py
  Metallicity_Stack_Commons/plotting/balmer.py
Labels: enhancement

#60 feature/suffixes
  Metallicity_Stack_Commons/column_names.py
Labels: enhancement, organization

#61 hotfix/1.1.1
  Metallicity_Stack_Commons/analysis/attenuation.py
  Metallicity_Stack_Commons/column_names.py
Labels: enhancement

#63 hotfix/1.1.2
  Metallicity_Stack_Commons/analysis/error_prop.py
Labels: bug
